[haad@ ~]$ ssh 192.168.105.65 -l root
[root@iscsi ~]# vim /etc/yum.conf 

[main]
cachedir=/var/cache/yum
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
distroverpkg=redhat-release
tolerant=1
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1

# Note: yum-RHN-plugin doesn't honor this.
metadata_expire=1h

# Default.
# installonly_limit = 3

# PUT YOUR REPOS HERE OR IN separate files named file.repo
# in /etc/yum.repos.d

[oracle5u5]
name=oracle5u5
baseurl=ftp://192.168.100.8/pub/5u5/Server/
gpgkey=ftp://192.168.100.8/pub/5u5/RPM-GPG-KEY
gpgkey=ftp://192.168.100.8/pub/5u5/RPM-GPG-KEY-oracle

proxy=http://192.168.100.8:3128


public-yum-el5.repo.disable
[root@iscsi yum.repos.d]# mv public-yum-el5.repo.disable public-yum-el5.repo
[root@iscsi yum.repos.d]# yum update
Loaded plugins: security
el5_addons                                                                                                                                    |  951 B     00:00     
el5_addons/primary                                                                                                                            |  19 kB     00:00     
el5_addons                                                                                                                                                     70/70
el5_oracle_addons                                                                                                                             |  951 B     00:00     
el5_oracle_addons/primary                                                                                                                     | 1.7 kB     00:00     
el5_oracle_addons                                                                                                                                                7/7
ol5_u5_base                                                                                                                                   |  951 B     00:00     
ol5_u5_base/primary                                                                                                                           |  14 kB     00:00     
ol5_u5_base                                                                                                                                                    53/53
oracle5u5                                                                                                                                     | 1.1 kB     00:00     
Skipping security plugin, no data
Setting up Update Process
Resolving Dependencies
Skipping security plugin, no data
--> Running transaction check
---> Package device-mapper-multipath.x86_64 0:0.4.9-23.0.4.el5 set to be updated
--> Processing Dependency: device-mapper-multipath-libs = 0.4.9-23.0.4.el5 for package: device-mapper-multipath
--> Processing Dependency: libmultipath.so()(64bit) for package: device-mapper-multipath
---> Package irqbalance.x86_64 2:0.55-16.el5 set to be updated
---> Package kernel.x86_64 0:2.6.32-100.0.19.el5 set to be installed
--> Processing Dependency: kernel-firmware >= 2.6.32-100.0.19.el5 for package: kernel
--> Processing Dependency: ql2xxx-firmware for package: kernel
--> Processing Dependency: oraclelinux-release for package: kernel
---> Package kexec-tools.x86_64 0:1.102pre-96.1.1.el5_5.2 set to be updated
---> Package kpartx.x86_64 0:0.4.9-23.0.4.el5 set to be updated
---> Package libbdevid-python.x86_64 0:5.1.19.6-61.0.3.el5_5.2 set to be updated
---> Package mcelog.x86_64 1:0.9pre-1.30.el5 set to be updated
---> Package mkinitrd.i386 0:5.1.19.6-61.0.3.el5_5.2 set to be updated
---> Package mkinitrd.x86_64 0:5.1.19.6-61.0.3.el5_5.2 set to be updated
---> Package nash.x86_64 0:5.1.19.6-61.0.3.el5_5.2 set to be updated
---> Package net-snmp-libs.i386 1:5.3.2.2-9.0.1.el5_5.1 set to be updated
---> Package net-snmp-libs.x86_64 1:5.3.2.2-9.0.1.el5_5.1 set to be updated
---> Package util-linux.x86_64 0:2.13-0.52.0.1.el5_4.1 set to be updated
--> Running transaction check
---> Package device-mapper-multipath-libs.x86_64 0:0.4.9-23.0.4.el5 set to be updated
---> Package kernel-firmware.x86_64 0:2.6.32-100.0.19.el5 set to be updated
---> Package oraclelinux-release.x86_64 0:5-5.0.2 set to be updated
---> Package ql2xxx-firmware.noarch 0:1.01.01-0.1.el5 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================
 Package                                           Arch                        Version                                        Repository                        Size
=====================================================================================================================================================================
Installing:
 kernel                                            x86_64                      2.6.32-100.0.19.el5                            ol5_u5_base                       23 M
Updating:
 device-mapper-multipath                           x86_64                      0.4.9-23.0.4.el5                               ol5_u5_base                       83 k
 irqbalance                                        x86_64                      2:0.55-16.el5                                  ol5_u5_base                       21 k
 kexec-tools                                       x86_64                      1.102pre-96.1.1.el5_5.2                        ol5_u5_base                      576 k
 kpartx                                            x86_64                      0.4.9-23.0.4.el5                               ol5_u5_base                      452 k
 libbdevid-python                                  x86_64                      5.1.19.6-61.0.3.el5_5.2                        ol5_u5_base                       64 k
 mcelog                                            x86_64                      1:0.9pre-1.30.el5                              ol5_u5_base                       31 k
 mkinitrd                                          i386                        5.1.19.6-61.0.3.el5_5.2                        ol5_u5_base                      472 k
 mkinitrd                                          x86_64                      5.1.19.6-61.0.3.el5_5.2                        ol5_u5_base                      460 k
 nash                                              x86_64                      5.1.19.6-61.0.3.el5_5.2                        ol5_u5_base                      1.4 M
 net-snmp-libs                                     i386                        1:5.3.2.2-9.0.1.el5_5.1                        ol5_u5_base                      1.3 M
 net-snmp-libs                                     x86_64                      1:5.3.2.2-9.0.1.el5_5.1                        ol5_u5_base                      1.3 M
 util-linux                                        x86_64                      2.13-0.52.0.1.el5_4.1                          ol5_u5_base                      1.8 M
Installing for dependencies:
 device-mapper-multipath-libs                      x86_64                      0.4.9-23.0.4.el5                               ol5_u5_base                      153 k
 kernel-firmware                                   x86_64                      2.6.32-100.0.19.el5                            ol5_u5_base                      1.0 M
 oraclelinux-release                               x86_64                      5-5.0.2                                        ol5_u5_base                      2.3 k
 ql2xxx-firmware                                   noarch                      1.01.01-0.1.el5                                ol5_u5_base                      451 k

Transaction Summary
=====================================================================================================================================================================
Install       5 Package(s)
Upgrade      12 Package(s)

Total download size: 32 M
Is this ok [y/N]: Exiting on user Command
Complete!
[root@iscsi yum.repos.d]# rpm -ivh /tmp/
.font-unix/                                              perl-Config-General-2.40-1.el5.noarch.rpm
.ICE-unix/                                               public-yum-el5.repo.disable
libibverbs-1.1.3-2.el5.x86_64.rpm                        scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm
librdmacm-1.0.10-1.el5.x86_64.rpm                        vmware-root/
[root@iscsi yum.repos.d]# rpm -ivh /tmp/scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm 
warning: /tmp/scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm: Header V3 DSA signature: NOKEY, key ID e8562897
error: Failed dependencies:
	libibverbs.so.1()(64bit) is needed by scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64
	librdmacm.so.1()(64bit) is needed by scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64
	perl(Config::General) is needed by scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64
[root@iscsi yum.repos.d]# yum install libibverbs
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package libibverbs.i386 0:1.1.3-2.el5 set to be updated
--> Processing Dependency: openib >= 1.0 for package: libibverbs
--> Processing Dependency: libibverbs-driver for package: libibverbs
---> Package libibverbs.x86_64 0:1.1.3-2.el5 set to be updated
--> Running transaction check
---> Package libnes.i386 0:0.9.0-2.el5 set to be updated
---> Package openib.noarch 0:1.4.1-5.el5 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================
 Package                                 Arch                                Version                                    Repository                              Size
=====================================================================================================================================================================
Installing:
 libibverbs                              i386                                1.1.3-2.el5                                oracle5u5                               45 k
 libibverbs                              x86_64                              1.1.3-2.el5                                oracle5u5                               45 k
Installing for dependencies:
 libnes                                  i386                                0.9.0-2.el5                                oracle5u5                               13 k
 openib                                  noarch                              1.4.1-5.el5                                oracle5u5                               21 k

Transaction Summary
=====================================================================================================================================================================
Install       4 Package(s)
Upgrade       0 Package(s)

Total download size: 123 k
Is this ok [y/N]: y
Downloading Packages:
(1/4): libnes-0.9.0-2.el5.i386.rpm                                                                                                            |  13 kB     00:00     
(2/4): openib-1.4.1-5.el5.noarch.rpm                                                                                                          |  21 kB     00:00     
(3/4): libibverbs-1.1.3-2.el5.x86_64.rpm                                                                                                      |  45 kB     00:00     
(4/4): libibverbs-1.1.3-2.el5.i386.rpm                                                                                                        |  45 kB     00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                2.3 MB/s | 123 kB     00:00     
warning: rpmts_HdrFromFdno: Header V3 DSA signature: NOKEY, key ID 1e5e0159
oracle5u5/gpgkey                                                                                                                              | 1.4 kB     00:00     
Importing GPG key 0x1E5E0159 "Oracle OSS group (Open Source Software group) <build@oss.oracle.com>" from ftp://192.168.100.8/pub/5u5/RPM-GPG-KEY-oracle
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : openib                                                                                                                                        1/4 
  Installing     : libnes                                                                                                                                        2/4 
  Installing     : libibverbs                                                                                                                                    3/4 
  Installing     : libibverbs                                                                                                                                    4/4 

Installed:
  libibverbs.i386 0:1.1.3-2.el5                                                    libibverbs.x86_64 0:1.1.3-2.el5                                                   

Dependency Installed:
  libnes.i386 0:0.9.0-2.el5                                                        openib.noarch 0:1.4.1-5.el5                                                       

Complete!
[root@iscsi yum.repos.d]# yum install librdmacm
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package librdmacm.i386 0:1.0.10-1.el5 set to be updated
---> Package librdmacm.x86_64 0:1.0.10-1.el5 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================
 Package                                Arch                                Version                                     Repository                              Size
=====================================================================================================================================================================
Installing:
 librdmacm                              i386                                1.0.10-1.el5                                oracle5u5                               23 k
 librdmacm                              x86_64                              1.0.10-1.el5                                oracle5u5                               22 k

Transaction Summary
=====================================================================================================================================================================
Install       2 Package(s)
Upgrade       0 Package(s)

Total download size: 45 k
Is this ok [y/N]: y
Downloading Packages:
(1/2): librdmacm-1.0.10-1.el5.x86_64.rpm                                                                                                      |  22 kB     00:00     
(2/2): librdmacm-1.0.10-1.el5.i386.rpm                                                                                                        |  23 kB     00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                2.1 MB/s |  45 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : librdmacm                                                                                                                                     1/2 
  Installing     : librdmacm                                                                                                                                     2/2 

Installed:
  librdmacm.i386 0:1.0.10-1.el5                                                    librdmacm.x86_64 0:1.0.10-1.el5                                                   

Complete!
[root@iscsi yum.repos.d]# ls -la /tmp/
-rw-r--r--  1 root root  45551 Feb  4 00:27 libibverbs-1.1.3-2.el5.x86_64.rpm
-rw-r--r--  1 root root  23367 Feb  4 00:27 librdmacm-1.0.10-1.el5.x86_64.rpm
-rw-r--r--  1 root root  69876 Feb  4 00:27 perl-Config-General-2.40-1.el5.noarch.rpm
-rw-r--r--  1 root root   2308 Feb  4 00:27 public-yum-el5.repo.disable
-rw-r--r--  1 root root 146322 Feb  4 00:27 scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm
[root@iscsi yum.repos.d]# rpm -ivh /tmp/perl-Config-General-2.40-1.el5.noarch.rpm
warning: /tmp/perl-Config-General-2.40-1.el5.noarch.rpm: Header V3 DSA signature: NOKEY, key ID e8562897
Preparing...                ########################################### [100%]
   1:perl-Config-General    ########################################### [100%]
[root@iscsi yum.repos.d]# rpm -ivh /tmp/scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm 
warning: /tmp/scsi-target-utils-0.0-6.20091205snap.el5_5.3.x86_64.rpm: Header V3 DSA signature: NOKEY, key ID e8562897
Preparing...                ########################################### [100%]
   1:scsi-target-utils      ########################################### [100%]
[root@iscsi yum.repos.d]# chkconfig tgtd on
[root@iscsi yum.repos.d]# lvm lvdisplay
  /dev/hdc: open failed: No medium found
  --- Logical volume ---
  LV Name                /dev/vg_iscsi/media
  VG Name                vg_iscsi
  LV UUID                daCLbE-6L9V-Itt4-Ds2f-sF3Y-59Tv-b9zQJY
  LV Write Access        read/write
  LV Status              available
  # open                 0
  LV Size                800.00 GB
  Current LE             204800
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:2
   
  --- Logical volume ---
  LV Name                /dev/vg_iscsi/temp
  VG Name                vg_iscsi
  LV UUID                xhf13R-qS6I-fj3S-ZQfE-J3eZ-Ao7m-jrdQHi
  LV Write Access        read/write
  LV Status              available
  # open                 0
  LV Size                30.00 GB
  Current LE             7680
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:3                                                                                                 
[root@iscsi yum.repos.d]# /etc/init.d/tgtd restart
Stopping SCSI target daemon:                               [  OK  ]
Starting SCSI target daemon: Starting target framework daemon

[root@iscsi yum.repos.d]# yum install iscsi-initiator-utils
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package iscsi-initiator-utils.x86_64 0:6.2.0.871-0.16.el5 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================
 Package                                        Arch                            Version                                     Repository                          Size
=====================================================================================================================================================================
Installing:
 iscsi-initiator-utils                          x86_64                          6.2.0.871-0.16.el5                          oracle5u5                          811 k

Transaction Summary
=====================================================================================================================================================================
Install       1 Package(s)
Upgrade       0 Package(s)

Total download size: 811 k
Is this ok [y/N]: y
Downloading Packages:
iscsi-initiator-utils-6.2.0.871-0.16.el5.x86_64.rpm                                                                                           | 811 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : iscsi-initiator-utils                                                                                                                         1/1 

Installed:
  iscsi-initiator-utils.x86_64 0:6.2.0.871-0.16.el5                                                                                                                  

Complete!
[root@iscsi yum.repos.d]# vim /etc/tgt/targets.conf 

# This is a sample config file for tgt-admin.
# By default, tgt-admin looks for its config file in /etc/tgt/targets.conf
#
# The "#" symbol disables the processing of a line.


# This one includes other config files:

#include /etc/tgt/temp/*.conf


# Set the driver. If not specified, defaults to "iscsi".

default-driver iscsi


# Continue if tgtadm exits with non-zero code (equivalent of
# --ignore-errors command line option)
#ignore-errors yes


# Sample target with one LUN only. Defaults to allow access for all initiators:

<target iqn.2011-02.sk.reality:iscsi.media>
    backing-store /dev/vg_iscsi/media
</target>

<target iqn.2011-02.sk.reality:iscsi.temp>
    backing-store /dev/vg_iscsi/temp
</target>

[root@iscsi yum.repos.d]# tgtadm --lld iscsi --op show --mode target
Target 1: iqn.2011-02.sk.reality:iscsi.media
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00010000
            SCSI SN: beaf10
            Size: 0 MB
            Online: Yes
            Removable media: No
            Backing store type: rdwr
            Backing store path: None
        LUN: 1
            Type: disk
            SCSI ID: IET     00010001
            SCSI SN: beaf11
            Size: 858993 MB
            Online: Yes
            Removable media: No
            Backing store type: rdwr
            Backing store path: /dev/vg_iscsi/media
    Account information:
    ACL information:
        ALL
Target 2: iqn.2011-02.sk.reality:iscsi.temp
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00020000
            SCSI SN: beaf20
            Size: 0 MB
            Online: Yes
            Removable media: No
            Backing store type: rdwr
            Backing store path: None
        LUN: 1
            Type: disk
            SCSI ID: IET     00020001
            SCSI SN: beaf21
            Size: 32212 MB
            Online: Yes
            Removable media: No
            Backing store type: rdwr
            Backing store path: /dev/vg_iscsi/temp
    Account information:
    ACL information:
        ALL
[root@iscsi yum.repos.d]#